### ISSUE TITLE
Does not run under PHP8

### ISSUE THREAD

**Issue by derunterstrich** [bnomei/kirby3-doctor#23]
We have moved the project to PHP 8 as PHP 7.4 is EOL at the end of the year. Unfortunately, one dependency does not tolerate the change:

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - bnomei/kirby3-doctor[1.5.0, ..., 1.5.1] require zendframework/zenddiagnostics ^1.6 -> satisfiable by zendframework/zenddiagnostics[v1.6.0].
>     - zendframework/zenddiagnostics v1.6.0 requires php ^5.6 || ^7.0 -> your php version (8.0.13) does not satisfy that requirement.
>     - Root composer.json requires bnomei/kirby3-doctor ^1.5 -> satisfiable by bnomei/kirby3-doctor[1.5.0, 1.5.1].

**Comment by RLLNGR** [comment]
I also have this issue when I try to install it with composer

**Comment by bnomei** [comment]
will be fixed in ucoming v2

**Comment by bnomei** [comment]
https://github.com/bnomei/kirby3-doctor/releases/tag/v2.0.0

you will have to remove and require again with composer. just upgrading will not upgrade from v1 to v2.
